dotenv: .env
networks:
    development:
        verify_flag: False
    rinkeby:        
        verify_flag: True
    kovan:        
        verify_flag: True
    polygon-mumbai:
        verify_flag: True
wallets:
    from_key: ${PRIVATE_KEY}
    
